Lang = {
    ['invalid_string'] = 'Invalid value provided.',
    ['not_enough_money'] = 'You do not have enough money.',
    ['company_purchased'] = 'Company purchased for $%s.',
    ['company_renamed'] = 'Company renamed successfully.',
    ['company_sold'] = 'You sold the company and received $%s.',
    ['company_owned'] = 'You already own a company.',
    ['company_unowned'] = 'This company is not owned.',
    ['company_locked'] = 'You do not have access to this company.',
    ['company_requires_certificate'] = 'This delivery tier requires a company certificate.',
    ['company_requires_level'] = 'This delivery tier requires level %s.',
    ['company_certificate_bought'] = 'Certificate purchased successfully.',
    ['company_certificate_missing_funds'] = 'You do not have enough money for the certificate.',
    ['company_certificate_owned'] = 'The company already owns a certificate.',
    ['company_purchase_confirm'] = 'Confirm purchase: $%s',
    ['company_sell_confirm'] = 'Sell company for $%s?',
    ['company_name_prompt'] = 'Company name',
    ['company_name_placeholder'] = 'Enter company name',
    ['company_menu_title'] = 'Delivery Company',
    ['menu_purchase_company'] = 'Purchase company',
    ['menu_request_job'] = 'Request job',
    ['delivery_interact'] = 'Press [E] to complete delivery',
    ['menu_rename_company'] = 'Rename company',
    ['menu_sell_company'] = 'Sell company',
    ['menu_certificate'] = 'Buy certificate',
    ['menu_level'] = 'Company level: %s',
    ['menu_current_vehicle'] = 'Vehicle: %s ($%s deposit)',
    ['menu_choose_vehicle'] = 'Choose vehicle',
    ['menu_choose_tier'] = 'Choose delivery tier',
    ['menu_cancel_job'] = 'Cancel current delivery',
    ['menu_boss_actions'] = 'Boss actions',
    ['company_updated'] = 'Company data updated.',

    ['draw_company_menu'] = 'Press [E] to open the company terminal',
    ['draw_company_locked'] = 'Access restricted',

    ['job_no_routes'] = 'No routes available right now.',
    ['job_in_progress'] = 'You already have an active delivery.',
    ['job_started'] = 'Delivery route assigned. Complete all stops.',
    ['job_completed'] = 'Delivery complete. Payment received.',
    ['job_cancelled'] = 'Delivery cancelled.',
    ['job_vehicle_invalid'] = 'This vehicle is not approved for the contract.',
    ['job_location_invalid'] = 'This delivery point is not part of the route.',
    ['job_double_payment_blocked'] = 'Delivery already processed.',
    ['job_timeout'] = 'Delivery expired before completion.',
    ['job_deposit_paid'] = '$%s deposit paid.',
    ['job_deposit_returned'] = '$%s deposit returned.',
    ['job_deposit_withheld'] = 'Deposit withheld due to damages.',

    ['input_company_name'] = 'Company Name',
    ['input_optional'] = 'Optional',

    ['context_close'] = 'Close'
}
