-- ## USE THIS TO ADD COLUMNS IN YOUR owned_vehicles TABLE IN DATABASE ## --

ALTER TABLE player_vehicles
ADD COLUMN IF NOT EXISTS t1ger_keys TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS t1ger_alarm TINYINT(1) NOT NULL DEFAULT 0;